// Code generated by goctl. DO NOT EDIT.
package types

type ReqLoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

type RespLoginUser struct {
	Code     int64     `json:"code"`
	Msg      string    `json:"message"`
	Token    string    `json:"token"`
	UserInfo *UserInfo `json:"userinfo"`
}

type ReqAddUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MsgResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"message"`
}

type UserId struct {
	Id int64 `json:"id"`
}
