// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"blog/rpc/user/internal/logic"
	"blog/rpc/user/internal/svc"
	"blog/rpc/user/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.ReqLoginUser) (*user.RespLoginUser, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Add(ctx context.Context, in *user.ReqAddUser) (*user.MsgResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *UserServer) Get(ctx context.Context, in *user.UserId) (*user.UserInfo, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
