version: '3.9'
services:
  frontend:
    image: docker_vue_develop_image
    container_name: docker_vue_develop_container
    build:
      context: .
      dockerfile: ./dockerfiles/Dev.dockerfile
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    ports:
      - "5173:3000"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","dev"]
