version: '3.9'
services:
  frontend:
    image: docker_vue_develop_image
    container_name: docker_vue_develop_container
    build:
      context: .
      dockerfile: ./dockerfiles/Dev.dockerfile
    volumes:
      - ".:/app"
      # 匿名卷
      - "./node_modules:/app/node_modules"
    ports:
      - "5173:5173"
