version: '3.9'
services:
  backend:
    image: docker_develop_image
    container_name: docker_develop_container
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "${BACKEND_PORT}:80"
      - "${DEBUG_PORT}:4000"
    depends_on:
      - redis
    networks:
      - app-network
    restart: always
    volumes:
      - ./logs:/logs
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network
    restart: always
    volumes:
      - ./data:/data
networks:
  app-network:
    driver: bridge
