// Code generated by goctl. DO NOT EDIT.
package types

type ReqLoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RespLoginUser struct {
	Token string `json:"token"`
}

type ReqAddUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MsgResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"message"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserId struct {
	Id int64 `json:"id"`
}
